# Mean and Varience

Problem statement :\
Create a data set of 200 entries (could be anything age, marks, height, weight
etc.). To get unbiased estimation, using a random function generator, collect
15 set samples of data of 10 classes having 20 entries each. Calculate the
mean and variance of each sample classes as well as the population (of 200).
Note down your observations.

In [2]:
#loading required package
import numpy as np
import random

generateClass(class_range) : generate classes for each field depending on range \
    for example: \
    field = age \
    range = 18-60 \
    data will be generated for 20 data items between 18-60 \
    This will be repeated for every field to generate class

generateSample():  generates sample containing 10 class each having 20 entries in each field(age,height,wieght,...)


In [3]:
 def generateClass(class_range):
    age = np.random.randint(class_range[0][0],class_range[0][1],20)
    height = np.random.randint(class_range[1][0],class_range[1][1],20)
    weight = np.random.randint(class_range[2][0],class_range[2][1],20)
    iq = np.random.randint(class_range[3][0],class_range[3][1],20)
    salary_per_day = np.random.randint(class_range[4][0],class_range[4][1],20)
    sleep_hour = np.random.randint(class_range[5][0],class_range[5][1],20)
    marks = np.random.randint(class_range[6][0],class_range[6][1],20)
    avg_distance = np.random.randint(class_range[7][0],class_range[7][1],20)
    sugar_level = np.random.randint(class_range[8][0],class_range[8][1],20)
    blood_pressure = np.random.randint(class_range[9][0],class_range[9][1],20)
    return [age,height,weight,iq,salary_per_day,sleep_hour,marks,avg_distance,sugar_level,blood_pressure]
    
def generateSample():
    cr1 = [(18,60,),(150,190),(50,120),(70,120),(500,1500),(4,9),(60,100),(1,5),(80,200),(60,150)]
    cr2 = [(18,25,),(150,190),(60,100),(90,120),(300,1000),(4,8),(65,100),(1,9),(80,140),(70,140)]
    cr3 = [(25,50,),(150,190),(50,130),(80,120),(600,2400),(4,7),(60,100),(1,8),(80,200),(60,150)]
    cr4 = [(50,60,),(140,180),(50,110),(70,100),(500,1700),(6,9),(50,85),(1,5),(60,200),(55,150)]
    cr5 = [(25,30,),(160,190),(60,120),(80,130),(400,2000),(4,7),(75,100),(1,8),(80,170),(75,140)]
    cr6 = [(30,60,),(150,190),(60,120),(80,120),(600,2500),(4,9),(70,100),(1,5),(80,210),(60,150)]
    cr7 = [(5,20, ),(130,190),(20,80),(70,120),(1,800),(6,10),(40,90),(1,4),(80,200),(80,140)]
    cr8 = [(20,40,),(155,190),(50,120),(80,120),(500,1200),(4,8),(60,100),(1,8),(80,200),(70,140)]
    cr9 = [(40,60,),(145,180),(50,120),(70,100),(200,2000),(6,9),(40,90),(1,6),(90,200),(60,145)]
    cr10 = [(60,75,),(130,170),(50,120),(70,90),(100,300),(7,9),(40,80),(1,4),(50,210),(50,150)]
    class_range = [cr1,cr2,cr3,cr4,cr5,cr6,cr7,cr8,cr9,cr10]
    sample = []
    for cr in class_range:
        c = generateClass(cr)
        sample.append(c)
    return sample
generateSample() #generating a sample

[[array([27, 22, 55, 39, 55, 51, 33, 37, 27, 53, 31, 50, 27, 43, 27, 35, 32,
         50, 25, 49]),
  array([167, 189, 182, 155, 175, 180, 175, 152, 157, 172, 185, 163, 173,
         163, 179, 176, 168, 182, 156, 173]),
  array([ 62, 117,  74, 100,  80,  58,  78,  62, 116,  72,  69, 108,  89,
         105,  84, 107,  58,  82,  69, 109]),
  array([ 90,  80, 115, 104,  79, 107, 104,  71, 100,  76, 107, 113, 110,
          84, 106,  76, 110,  99,  77,  86]),
  array([1224, 1272, 1064, 1356, 1031,  966,  819, 1214,  521, 1044, 1003,
         1148, 1262,  669, 1433,  697, 1399, 1295, 1474,  678]),
  array([6, 4, 6, 4, 4, 6, 5, 5, 7, 5, 7, 6, 7, 8, 7, 6, 8, 6, 7, 7]),
  array([88, 77, 78, 69, 62, 87, 86, 92, 86, 99, 85, 79, 61, 82, 68, 83, 70,
         87, 92, 64]),
  array([1, 2, 1, 1, 4, 4, 2, 4, 1, 2, 1, 3, 3, 2, 1, 1, 2, 4, 2, 3]),
  array([ 82,  81, 146, 191, 184, 122, 138, 170, 119,  81, 132, 131, 165,
         103, 190, 102, 174,  91, 194,  97]),
  array([ 66, 112,  94,  64, 130, 141,

In [9]:
# function to compute mean of data
# data = [d1,d2,....,dn]
def mean(data):
    sum_of_data = 0
    l=0
    for x in data:
        sum_of_data += x
        l += 1
    return sum_of_data/l

In [61]:
#function to compute varience of data
#data = [d1,d2,.....,dn]
#mean_data = mean of data
def varience(data,mean_data):
    s = 0
    n = 0
    for x in list(data):
        s += (x-mean_data)**2
        n += 1
    return s/(n-1)

In [4]:
#Generating all 15 sample one by one
sample_set = []
for i in range(0,15):
    sample = generateSample()
    sample_set.append(sample)
    

In [68]:
#for sample 1
#showing mean of each class and population
np.set_printoptions(suppress=True)      # for suppression of scientific notation while printing


i=1
mean_all = []
var_all = []
for class_i in sample_set[0]:
    mean_class=[]
    var_class=[]
    for field in class_i:
        mean_class.append(mean(field))
        var_class.append(varience(field,mean(field)))
        
    print("class = ",i)
    print(mean_class)
    print(list(np.around(var_class,2)))
    i += 1


for i in range(10):
    data_field = []
    for class_i in sample_set[0]:
        data_field += list(class_i[i])
    mean_all.append(mean(data_field))
    var_all.append(varience(data_field,mean(data_field)))
print("\n----------------------Population----------------------------")
print("Mean\n",mean_all)
print("Varience\n",list(np.around(var_all,2)))

[26 45 19 19 18 46 29 22 46 50 57 35 37 50 43 36 51 58 29 22]
36.9
class =  1
[36.9, 172.85, 78.35, 100.7, 1016.65, 6.05, 78.9, 2.5, 139.0, 98.1]
[176.31, 87.4, 420.24, 202.54, 68036.56, 2.89, 155.88, 1.42, 1744.95, 540.83]
class =  2
[21.2, 169.8, 78.5, 105.75, 677.3, 5.0, 79.75, 3.75, 105.85, 109.9]
[3.22, 126.8, 154.58, 44.2, 51153.8, 1.05, 120.2, 5.14, 258.98, 326.09]
class =  3
[37.55, 167.25, 91.85, 98.5, 1685.0, 4.85, 82.9, 4.1, 141.6, 99.15]
[55.31, 71.04, 530.56, 125.42, 265311.58, 0.56, 131.57, 5.67, 1032.46, 553.29]
class =  4
[53.6, 157.75, 80.8, 82.25, 1041.75, 6.95, 62.65, 2.95, 138.05, 98.35]
[9.62, 98.83, 272.8, 55.67, 157050.62, 0.68, 98.24, 1.31, 1556.89, 639.08]
class =  5
[26.9, 173.15, 85.35, 103.75, 971.95, 5.0, 87.4, 3.95, 133.7, 105.7]
[2.41, 78.34, 221.29, 267.67, 170307.42, 0.74, 74.67, 4.68, 560.85, 443.48]
class =  6
[46.45, 166.3, 83.7, 101.2, 1485.6, 6.0, 84.2, 2.55, 136.45, 106.35]
[45.84, 134.96, 217.38, 114.8, 268899.73, 2.32, 82.69, 1.63, 1433.21, 638.

In [73]:
#For all 15 samples
#Each sample contains mean for each class with respective field and for each whole population
np.set_printoptions(suppress=True)
s=1
for sample in sample_set:
    i=1
    j=1
    mean_all = []
    var_all = []
    print("\n\n\n\nSAMPLE -----------------------",s,"\n")
    for class_i in sample:
        mean_class=[]
        var_class=[]
        for field in class_i:
            mean_class.append(mean(field))
            var_class.append(varience(field,mean(field)))
    
        print("class ======= ",i)
        print(mean_class)
        print(list(np.around(var_class,2)))
        i += 1
    for i in range(10):
        data_field = []
        for class_i in sample:
            data_field += list(class_i[i])
        mean_all.append(mean(data_field))
        var_all.append(varience(data_field,mean(data_field)))
    print("----------------------------Population-----------------------")
    print("Mean\n",mean_all)
    print("Varience\n",list(np.around(var_all,2)))
    s += 1





SAMPLE ----------------------- 1 

class =======  1
[36.9, 172.85, 78.35, 100.7, 1016.65, 6.05, 78.9, 2.5, 139.0, 98.1]
[176.31, 87.4, 420.24, 202.54, 68036.56, 2.89, 155.88, 1.42, 1744.95, 540.83]
class =======  2
[21.2, 169.8, 78.5, 105.75, 677.3, 5.0, 79.75, 3.75, 105.85, 109.9]
[3.22, 126.8, 154.58, 44.2, 51153.8, 1.05, 120.2, 5.14, 258.98, 326.09]
class =======  3
[37.55, 167.25, 91.85, 98.5, 1685.0, 4.85, 82.9, 4.1, 141.6, 99.15]
[55.31, 71.04, 530.56, 125.42, 265311.58, 0.56, 131.57, 5.67, 1032.46, 553.29]
class =======  4
[53.6, 157.75, 80.8, 82.25, 1041.75, 6.95, 62.65, 2.95, 138.05, 98.35]
[9.62, 98.83, 272.8, 55.67, 157050.62, 0.68, 98.24, 1.31, 1556.89, 639.08]
class =======  5
[26.9, 173.15, 85.35, 103.75, 971.95, 5.0, 87.4, 3.95, 133.7, 105.7]
[2.41, 78.34, 221.29, 267.67, 170307.42, 0.74, 74.67, 4.68, 560.85, 443.48]
class =======  6
[46.45, 166.3, 83.7, 101.2, 1485.6, 6.0, 84.2, 2.55, 136.45, 106.35]
[45.84, 134.96, 217.38, 114.8, 268899.73, 2.32, 82.69, 1.63, 1433.

----------------------------Population-----------------------
Mean
 [37.79, 164.685, 82.56, 95.135, 928.725, 6.17, 74.09, 3.1, 132.61, 104.16]
Varience
 [290.14, 174.64, 520.46, 196.3, 294216.27, 1.98, 239.21, 3.26, 1306.18, 571.66]




SAMPLE ----------------------- 9 

class =======  1
[44.05, 170.4, 79.3, 98.95, 1066.2, 5.6, 81.15, 2.7, 132.8, 104.9]
[168.37, 124.99, 534.12, 220.16, 85223.33, 1.62, 145.5, 1.27, 1407.64, 643.25]
class =======  2
[20.45, 172.15, 81.4, 100.2, 653.45, 5.85, 83.35, 3.75, 109.0, 98.65]
[4.68, 135.92, 129.31, 62.48, 41736.58, 1.19, 81.08, 4.41, 319.05, 513.92]
class =======  3
[37.45, 167.95, 88.95, 102.2, 1547.55, 4.95, 79.95, 4.4, 136.35, 107.7]
[58.05, 99.73, 571.21, 113.64, 332444.58, 0.68, 124.89, 4.25, 1396.56, 566.12]
class =======  4
[54.4, 158.95, 82.0, 84.0, 1153.25, 7.1, 68.15, 2.7, 123.15, 102.9]
[10.25, 144.47, 340.95, 89.89, 93385.25, 0.73, 72.77, 1.17, 1060.66, 1067.25]
class =======  5
[27.35, 172.45, 88.35, 103.95, 1511.35, 5.15, 85.3, 4.7